### ISSUE TITLE
[APP REQUEST]: Socioboard

### ISSUE THREAD

**Issue by JoshuaMunoz** [SelfhostedPro/selfhosted_templates#120]
### Dockerhub Link: ###
https://github.com/socioboard/Socioboard-4.0

### Description ###
Socioboard Core is an open source social media management, analytics and reporting platform. It supports nine social media networks. Using Socioboard Core you can monitor and manage multiple social media accounts and create useful reports and take business decisions based on them.

### Separate Database? ###
Socioboard-4.0 is comes up centralized API which is implemented in Node.js, Express, Mongoose and Sequelize ORM and Frontend has been integrated with PHP.

**Comment by nashosted** [comment]
Again, are we adding apps that use sub services that charge monthly fees? I don't see these being used very often. @SelfhostedPro, what are your thoughts on these type of apps?

**Comment by SelfhostedPro** [comment]
How do you feel about having them reach out to the developers and having them submit a pull request to add their app? I feel like this would be a good way to get these implemented without us needing to put resources towards them. It should be easy for any dev to do this with minimal effort.

**Comment by nashosted** [comment]
> How do you feel about having them reach out to the developers and having them submit a pull request to add their app? I feel like this would be a good way to get these implemented without us needing to put resources towards them. It should be easy for any dev to do this with minimal effort.  @nashosted 

Worth a try. And more potential sales for them so why wouldn’t they?

**Comment by SelfhostedPro** [comment]
My thoughts exactly. Would you be able to reach out to socioboard and see if they would submit it to our repo as a pull request @JoshuaMunoz ?

**Comment by JoshuaMunoz** [comment]
Dang, am I misreading? I thought the open source, self-hosted side of it was free. The .com, paid side of it was, well, paid. Like if they're doing all the work/hosting, etc.
