### ISSUE TITLE
[APP REQUEST]: IG Monitoring

### ISSUE THREAD

**Issue by JoshuaMunoz** [SelfhostedPro/selfhosted_templates#121]
### Dockerhub Link: ###
https://github.com/jakim/ig-monitoring

### Description ###
Free, self hosted Instagram Analytics and Stats

### Separate Database? ###
You need WORKING proxies (at least 2).

You need a server (vps will be ok) with linux, root access and configured LEMP, that is:

php minimum 7.2
latest nginx, recommended server configuration
mysql minimum 5.7

**Comment by nashosted** [comment]
Not sure how I feel adding services that require monthly fees. I'd prefer sticking to FOSS applications.

**Comment by JoshuaMunoz** [comment]
That's fair. There is a free version, though.
