### ISSUE TITLE
[APP REQUEST]: Pritunl with OpenVPN & Wireguard

### ISSUE THREAD

**Issue by curator888** [SelfhostedPro/selfhosted_templates#133]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/SelfhostedPro/selfhosted_templates/issues/133)

### Dockerhub Link: ###
https://hub.docker.com/r/goofball222/pritunl

### Description ###
Pritunl container built on Alpine Linux. Supports IPv6 and running behind a reverse proxy.

### Separate Database? ###
This container requires an external Mongo DB and should be run via Docker Compose or other orchestration.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars1.githubusercontent.com/u/47480699?v=4' alt='curator888' width=24 height=24> curator888](https://issuehunt.io/u/curator888) ($50.00)

### Submitted pull Requests
- [#185 Fix Pritunl deployment error](https://issuehunt.io/r/SelfhostedPro/selfhosted_templates/pull/185)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/SelfhostedPro/selfhosted_templates/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by SelfhostedPro** [comment]
Getting a deployment error from portainer that I haven't had time to check. Ideally I'll be able to sometime soon.
