### ISSUE TITLE
[APP REQUEST]: Wallabag

### ISSUE THREAD

**Issue by AndyYangUK** [SelfhostedPro/selfhosted_templates#151]
### Dockerhub Link: ###
https://hub.docker.com/r/wallabag/wallabag/

### Description ###
wallabag is a self hostable application for saving web pages. Unlike other services, wallabag is free (as in freedom) and open source.

With this application you will not miss content anymore. Click, save, read it when you want. It saves the content you select so that you can read it when you have time.

### Separate Database? ###
SQLite or MySQL/MariaDB

**Comment by jake-walker** [comment]
I'd like to work on this one
