### ISSUE TITLE
Template error: unable to retrieve templates

### ISSUE THREAD

**Issue by chest069** [SelfhostedPro/selfhosted_templates#159]
The template.json file results in an "unable to retrieve templates" error when loading the App Templates page.

**Comment by curator888** [comment]
Are you using this exact url for your templates? https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Template/template.json

**Comment by ironboy1** [comment]
same for me, getting the same error message

**Comment by ironboy1** [comment]
The reason for this issue on my side is that I updated to portainer 2.0,which currently not supporting application templates.

**Comment by DavidPesticcio** [comment]
@chest069 / @ironboy1 

FYI I'm using the link below with Portainer **2.0.0** (it's documented somewhere, I had the same issue as you, but I can't find the link sorry) - it seems to be missing a lot of the entries from the original "Portainer" list... not sure why. :-(

[https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/portainer-2.0/Template/template.json](https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/portainer-2.0/Template/template.json)

HTH

**Comment by farizno** [comment]
@DavidPesticcio Thanks so much! This is what I needed to fix the issue in Portainer 2.0.

**Comment by SelfhostedPro** [comment]
There's a portainer 2.0 branch for Yacht now. Once I hit a slow down with Yacht I'll be getting some more work done on these templates. Not sure why there's less entries in the 2.0 branch but I'll see about resolving that.

**Comment by DavidPesticcio** [comment]
Hi @selfhostedpro - just to clarify my remark regarding "less" - I should have been more clear to point out that the template entries between selfhosted_templates & Portainer 2.0 templates does not appear to be an extended "mirror" of the original entries. While there are more in the selfhosted_templates list, there appear to be entries missing when compared to the original Portainer 2.0 entries. Hopefully that clarifies my point 🤓

Thanks for looking into it. If you would like some assistance with organising/synchronising the entries, feel free to ping me. I'm more than happy to assist wherever possible... ☺️👍

**Comment by SelfhostedPro** [comment]
@DavidPesticcio that would be much appreciated. I'm currently spending most of my time on Yacht so I haven't had time for these. Do you have a discord? If you do, join our server and I can run you through what's needed. 

https://discord.gg/KpKutvC

**Comment by Normanras** [comment]
This thread solved it for me too! I was originally looking for the app template file, as another issue mentioned incorrect brackets in certain places, but the 2.0 is what made it work. Thanks, all!
