### ISSUE TITLE
[APP REQUEST]: UniFi Video Controller

### ISSUE THREAD

**Issue by curator888** [SelfhostedPro/selfhosted_templates#161]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/SelfhostedPro/selfhosted_templates/issues/161)

### Dockerhub Link: ###
https://hub.docker.com/r/pducharme/unifi-video-controller

### Description ###
This docker image runs the unifi-video controller on Ubuntu. Originally intended for Unraid 6.x, it should run fine anywhere.

Restart the docker, visit http://localhost:7080 or http://<ip.address>:7080/ to start the Unifi Video wizard.

### Separate Database? ###
Yes

### Fill this out as best as you can. Documentation about these can be found here: https://www.portainer.io/documentation/how-to-use-templates/

```json
{
    "type": 1,
    "title": "UniFi Video",
    "name": "UniFi Video",
    "description": "UniFi Video is a powerful and flexible, integrated IP video management surveillance system designed to work with Ubiquiti’s UniFi Video Camera product line. UniFi Video has an intuitive, configurable, and feature‑packed user interface with advanced features such as motion detection, auto‑discovery, user‑level security, storage management, reporting, and mobile device support.",
    "logo": "https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/UniFiVideo-logo.png",
    "image": "pducharme/unifi-video-controller:latest",
    "categories": [
      "CCTV"
    ],
    "platform": "linux",
    "restart_policy": "unless-stopped",
    "ports": [
      "1935:1935/tcp, 7444:7444/tcp, 7447:7447/tcp, 6666:6666/tcp, 7442:7442/tcp, 7080:7080/tcp, 7443:7443/tcp, 7445:7445/tcp, 7446:7446/tcp"
    ],
    "volumes": [
      {
        "container": "/recordings",
        "bind": "/portainer/Files/AppData/Config/UnifFiVideo/Recordings/"
      }
      {
        "container": "/config",
        "bind": "/portainer/Files/AppData/Config/UniFiVideo/"
      }
    ],
    "env": [
      {
        "name": "PUID",
        "label": "PUID",
        "default": "99"
      },
      {
        "name": "PGID",
        "label": "PGID",
        "default": "100"
      },
      {
        "name": "UMASK",
        "label": "UMASK",
        "default": "002"
      },
      {
        "name": "CONTEXT_PATH",
        "label": "CONTEXT_PATH",
        "set": "UniFi Video"
      }
    ]
  },
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/SelfhostedPro/selfhosted_templates/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by siddharths2710** [comment]
Hey @curator888, just wanted to clarify one thing with respect to the issue. Since you have already added the template for the video controller as part of the pr, isn't it just a matter of appending the same config to the final template file [here](https://github.com/SelfhostedPro/selfhosted_templates/blob/master/Template/template.json) ?

**Comment by curator888** [comment]
@siddharths2710 Sorry yes it was a mistake, I know this will be added by the repo owner. Please feel free to grab the other bounties though.

**Comment by curator888** [comment]
This app is now EOL, and is now cloud based and called unifi protect.
