### ISSUE TITLE
Using these can I change the versions that are installed by default?

### ISSUE THREAD

**Issue by unabatedshagie** [SelfhostedPro/selfhosted_templates#170]
Does anyone know how (or if) I'm able to modify sonarr and radarr to use their v3 versions and have Plex update to the Plex Pass version?

**Comment by chest069** [comment]
I would like to know this as well

**Comment by unabatedshagie** [comment]
I don't know if this is the correct way or even if it'll break anything in the future but if you open the container then click on duplicate/edit and change the image of Sonarr to linuxserver/sonarr:preview and Radarr to linuxserver/radarr:preview then click on the redeploy button.

**Comment by SelfhostedPro** [comment]
That's the correct way for now.
