### ISSUE TITLE
Update template for Portainer CE 2.0

### ISSUE THREAD

**Issue by educatedCaveman** [SelfhostedPro/selfhosted_templates#175]
Using Portainer CE 2.0, one is unable to use this template.  When it is added as a custom template, Portainer says its unable to retrieve the template.  According to [this](https://www.portainer.io/2020/08/portainer-ce-2-0-what-to-expect/) blog post, there is a new format to be used, and they've provided a utility to convert it.  I've tried this on my own, and the one app I spot checked seemed fine.  Perhaps there should be a different version of the raw template made available?

**Comment by RikGeboers** [comment]
{
    "version": "2",
    "templates":
#copy template inside

}
--------------
its just a new format found out the issue as well recently

**Comment by C-Fu** [comment]
Somebody converted it already.

https://raw.githubusercontent.com/xe-nvdk/portainer_templates/master/Template/templates-2.0.json

**Comment by SelfhostedPro** [comment]
Looks like someone did a pull with the new format. It's in the portainer 2.0 branch now.
