### ISSUE TITLE
Differences of template format for branches

### ISSUE THREAD

**Issue by yangkghjh** [SelfhostedPro/selfhosted_templates#202]
Is there a manual to get start?

**Comment by kfridjonsson** [comment]
I am also interested in this. For some reason there is a gap somewhere at least for me
I am running OMV 5.5.13-1, Docker 5:19.03.13~3-0~debian-buster and Portainer 2.0.0 and there is no toggle under settings in my Portainer to enable external templates. There is how ever an URL field where there was already an URL I totally forgot to note, where I have tried putting in all template URLs I have found (OMV5, OMV5-2.0 and portainer 2.0) but no matter what I always get an error message: "Failure Unable to retrieve templates"

**Comment by pingywon** [comment]
Be sure you are running the latest ver. of yacht. I had this error at one point, but do not get it anymore.

Also here is an ARM template I have been working on to support Raspberry Pi and potentially other ARM devices. All apps tested on a Rpi4.

https://github.com/SelfhostedPro/selfhosted_templates/tree/pingywon-yacht-arm

**Comment by SelfhostedPro** [comment]
You'll just add them to the templates section in the respective application. There should be a url for raw.githubusercontent in each one that corresponds to the platform. I'm putting together a gui application to better maintain these as it's become difficult as of late.

**Comment by kfridjonsson** [comment]
> You'll just add them to the templates section in the respective application. There should be a url for raw.githubusercontent in each one that corresponds to the platform. I'm putting together a gui application to better maintain these as it's become difficult as of late.

The problem is not finding the correct URL for raw.githubusercontent. The problem is that Portainer has changed and now there is no toggle button to enable external templates. And there is only one possible field to input an URL and no matter from what branch an URL is used it doesn't work.

**Comment by SelfhostedPro** [comment]
> > You'll just add them to the templates section in the respective application. There should be a url for raw.githubusercontent in each one that corresponds to the platform. I'm putting together a gui application to better maintain these as it's become difficult as of late.
> 
> The problem is not finding the correct URL for raw.githubusercontent. The problem is that Portainer has changed and now there is no toggle button to enable external templates. And there is only one possible field to input an URL and no matter from what branch an URL is used it doesn't work.

https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/portainer-2.0/Template/template.json

Very top of the master readme.

**Comment by kfridjonsson** [comment]
Thank you. This solved this issue for me at least. :)

**Comment by slmingol** [comment]
Same, worked for me as well.

**Comment by yangkghjh** [comment]
Maintaining a page about the differences between templates

https://www.notion.so/Self-hosted-02c99bd53ae548ddaec14e1774595258
