### ISSUE TITLE
[BUG] template.json for Portainer 2.0 is not working on Portainer 2.0.1

### ISSUE THREAD

**Issue by eltonk** [SelfhostedPro/selfhosted_templates#220]
**Describe the bug**
I'm using Portainer 2.0.1 and tried to configure the Selhosted Templates for Portainer 2.0 using the following URL: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/portainer-2.0/Template/template.json

But the templates are not loaded to Portainer. No error is shown in the GUI or Logs.

**To Reproduce**
1. Go to 'Settings' on a Portainer 2.0.1 installation
2. On the 'App Templates' section, add the following URL: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/portainer-2.0/Template/template.json
2. Click on 'Save Settings'
3. On the Portainer left menu, click on 'App Templates'
4. No template is shown.

**Expected behavior**
A list of Selfhosted Templates for Portainer 2.0 is shown.

**Screenshots**
<img width="1680" alt="Screen Shot 2021-01-08 at 11 18 21 AM" src="https://user-images.githubusercontent.com/384042/104003811-3a072d00-51a3-11eb-92cf-89b68b4c84ae.png">
<img width="1679" alt="Screen Shot 2021-01-08 at 11 18 41 AM" src="https://user-images.githubusercontent.com/384042/104003849-468b8580-51a3-11eb-9816-92027f09f7d7.png">

**Comment by eltonk** [comment]
If you look for containers, it will appear. There is no issue, as the template file doesn't have any stack on it. This ticket is bein closed. Thanks all.

**Comment by marsimgit** [comment]
same issue here, no templates showed
