### ISSUE TITLE
[BUG] - Port v2.1.1 | Templates JSON | Unable to retrieve templates

### ISSUE THREAD

**Issue by quadcom** [SelfhostedPro/selfhosted_templates#226]
**Describe the bug**
I've added the URL for the JSON templates list. After saving and going to the App Templates in Portainer there was an error message at the top right. "Unable to retrieve templates"

**To Reproduce**
1. Add template JSON URL -> https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Template/template.json
2. Save
3. review templates availble

**Expected behavior**
I expected to see a list of 80+ app templates

**Portainer Logs**
today at 12:52 PM  2021/03/01 17:52:22 http error: Invalid request payload (err=Invalid external templates URL. Must correspond to a valid URL format) (code=400)

Would really like to see Portainer support multiple external template URLS. The v2.1.1 install came with a JSON already present in the templates field (https://raw.githubusercontent.com/portainer/templates/master/templates-2.0.json).

**Comment by FatherTusker** [comment]
From the Reddit thread, it appears that the correct URL for v2.0+ is https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/portainer-2.0/Template/template.json
Can confirm it works for me on 2.1.1 (running on OMV 5.6.2-1)
