### ISSUE TITLE
tt-rss image is not  working

### ISSUE THREAD

**Issue by nashosted** [SelfhostedPro/selfhosted_templates#30]
Failure
No such image: linuxserver/tt-rss:latest

**Comment by SelfhostedPro** [comment]
Is is a current image on linuxserver.io?

**Comment by SelfhostedPro** [comment]
This isn't available via linuxserver.io any longer. We'll need to remove it.

**Comment by emresaglam** [comment]
lunik1/tt-rss is a fork of the deprecated linuxserver.io tt-rss container if you want to replace tt-rss with it.

**Comment by SelfhostedPro** [comment]
Ooh perfect. I'll do that. Thanks!
