### ISSUE TITLE
Bitwarden_rs and Jellyfin

### ISSUE THREAD

**Issue by Oujiii** [SelfhostedPro/selfhosted_templates#36]
Hi! I love the project. 

Just creating a request to add whenever possible [Bitwarden_rs](https://hub.docker.com/r/bitwardenrs/server) and [Jellyfin](https://hub.docker.com/r/jellyfin/jellyfin/) which are two very popular services for self hosted enthusiasts.

Thank you very much.

**Comment by nashosted** [comment]
> Hi! I love the project.
> 
> Just creating a request to add whenever possible [Bitwarden_rs](https://hub.docker.com/r/bitwardenrs/server) and [Jellyfin](https://hub.docker.com/r/jellyfin/jellyfin/) which are two very popular services for self hosted enthusiasts.
> 
> Thank you very much.

Added Bitwarden_rs. I'll have SelfhostedPro add Jellyfin and merge to master. Expect an updated master within the next 24 hours :)

**Comment by SelfhostedPro** [comment]
Added in [https://github.com/SelfhostedPro/selfhosted_templates/commit/3a99e19506b77e058d2eb1361101aa84eec75bef](https://github.com/SelfhostedPro/selfhosted_templates/commit/3a99e19506b77e058d2eb1361101aa84eec75bef)
These are both available now.
