### ISSUE TITLE
BookStack - Default credentials fail for login after initial deployment?

### ISSUE THREAD

**Issue by joelrader** [SelfhostedPro/selfhosted_templates#50]
I can't figure out what I'm doing exactly to cause this, but now I can't login to the BookStack UI using the default credentials. My steps:

1. Deploy BookStack via App Templates
2. Login using 'admin@admin.com', 'password'
3. Change default login & password
4. Login fails? I might be using the wrong credentials?
5. Remove Stack in Portainer for BookStack, redeploy via App Tempate
6. Can't login with default credentials

It seems somehow I'm not properly uninstalling BookStack? It's failing to reset everything back to default?

**Comment by SelfhostedPro** [comment]
You'll have to delete the configuration in /portainer/Files/AppData/Bookstack (both the DB and Config folders)

**Comment by SelfhostedPro** [comment]
If that doesn't resolve it join our discord for some help: https://discord.gg/d7np9fX

**Comment by joelrader** [comment]
Thank you! That solved the issue. I just removed the BookStack directory and redeployed it, works now.  I also tried to deploy a second instance next to the first, but a second instance fails to run. Maybe that's expected.

Appreciate all the hard work!

**Comment by SelfhostedPro** [comment]
That's to be expected. You can manually change the bind mount in order to deploy a second one if needed. Will be a bit involved though since it's a stack template.
