### ISSUE TITLE
Sort the Template list

### ISSUE THREAD

**Issue by RobLoach** [SelfhostedPro/selfhosted_templates#55]
Alphabetical sort by key `title`.

**Comment by SelfhostedPro** [comment]
It's mostly alphabetical but we wanted to feature some apps as well. I guess it's gotten a bit out of hand and looks like a mess now. I'll cut down on the featured ones and sort them.

**Comment by RobLoach** [comment]
Once a few PRs are in, we could use some script to sort it how we want too :wink:

**Comment by SelfhostedPro** [comment]
Completed sorting everything. Those pull requests were awesome by the way! Love the automated testing.
