### ISSUE TITLE
nextcloud doesn't connect to mariadb

### ISSUE THREAD

**Issue by vmoalemi** [SelfhostedPro/selfhosted_templates#59]
I installed mariadb and then nextcloud separately using templates but nextcloud can not connect to database. I think they need some kind of stack file

**Comment by SelfhostedPro** [comment]
Fixed for you. It's now a stack template.

**Comment by rigler86** [comment]
nextcloud wont connect to the db that is installed via the stack

**Comment by SelfhostedPro** [comment]
Can you post what your settings were? Should be plug and play. What hardware are you using?

**Comment by dhcrain** [comment]
I am having the same/similar issue. 
Running on Raspberry Pi 4

TZ: america/chicago
DATABASE_PASSWORD: secret1 
MYSQL_ROOT_PASSWORD: secret2
PORT: 8088

**Comment by rigler86** [comment]
> I am having the same/similar issue. 
> Running on Raspberry Pi 4
> 
> TZ: america/chicago
> DATABASE_PASSWORD: secret1 
> MYSQL_ROOT_PASSWORD: secret2
> PORT: 8088
> 
> 

Go into portainer find ip of marian db in networks. Use that ip in nextcloud setup screen.
