### ISSUE TITLE
Feature Request: Add Invoice Ninja

### ISSUE THREAD

**Issue by curator888** [SelfhostedPro/selfhosted_templates#62]
Add Invoice Ninja, its a self hosted invoice and payment gateway.

https://github.com/invoiceninja/invoiceninja

**Comment by leonardoborlot** [comment]
Theres one error on the template. Whe you set the parameter and go to deploy, return erro do process.

**Comment by SelfhostedPro** [comment]
Yes. It's not working currently. I'm a bit busy working on another project and no one else is helping us out with Stack templates so it may be a while. Feel free to find out what's wrong with it and let me know and I'll change it when I get a moment.

**Comment by SelfhostedPro** [comment]
Should be resolved now. Please let me know if you continue to have trouble.
