### ISSUE TITLE
Doesnt Work on RaspberryPi 3 :(

### ISSUE THREAD

**Issue by bigdant** [SelfhostedPro/selfhosted_templates#68]
Hi,

Probably shows my lack of experience, but tried to install Whoogle as a test on my RapsberryPi 3 and it wont run.

Do you have a specific fork / JSON file specifically for ARM64, arm/v7, etc ?

Cheers

D

**Comment by SelfhostedPro** [comment]
You'll have to check the maintainer of the image we're using. It's likely they don't support it if it's not starting up. We may add one for raspberry pi's in the future but for right now we're working on getting the master branch up to date with the latest applications.

**Comment by bigdant** [comment]
Completely Understand!

It looks ACE by the way, maybe in the future you can create a master list that is then split out into forks based on the architecture supported.

Bit like:-

Architecture | Tag
-- | --
x86-64 | amd64-latest
arm64 | arm64v8-latest
armhf | arm32v7-latest

So something that supports x86-64 would'nt appear on the ARM64 list, etc ?

Cheers

Dan

**Comment by SelfhostedPro** [comment]
Definitely not a bad idea. This is the first github repo I've been working on that's gotten any traction so I'm not familiar with some of the best practices for things like that. For right now we've got a branch for standard linux (x86) and one for OpenMediaVault (OMV5). I'll talk to @nashosted and see what we want to do about that.

Thank you for the recommendations by the way!

**Comment by bigdant** [comment]
As i said, its ace !

Good luck.
