### ISSUE TITLE
ISSUE: cannot unmarshal string 

### ISSUE THREAD

**Issue by kanenses** [SelfhostedPro/selfhosted_templates#80]
I'am getting the follow error, when add:
https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/OMV5/Template/template.json

`Failure: json: cannot unmarshal string into Go struct field Template.interactive of type bool`

OMV5 (lastest) Portainer 1.24 and lastest docker.

**Comment by SelfhostedPro** [comment]
This was the result of an error when adding in ProtonMail Bridge. This should be resolved now. If you refresh the app templates page.
